### ISSUE TITLE
Are batch_size, gpu_num, and lr consistent?

### ISSUE THREAD

**Issue by 0xLDF** [OpenGVLab/Diffree#11]
In the [paper](https://arxiv.org/abs/2407.16982), 8 A100 GPUs are used with a batch size of 256. However, in the code, the number of GPUs is set to 4, and the batch size is 16.

I just want to check if the batch_size, gpu_num, and lr are consistent.

Thanks for your wonderful work.

**Comment by Lirui-Zhao** [comment]
Hi,

Thank you for your interest in our work! The paper describes the experimental setup in our initial version, subsequent trials revealed that comparable results could be obtained with fewer GPUs and smaller batch sizes. Hence, we have revised the recommended parameters on Diffree's repository. The Hugging Face weights were trained following the repository's updated configuration.

Best regards,
Lirui

**Comment by LPXTT** [comment]
Hi Lirui, I got a size miss matching issue when change GPU number from 4 to 8. The wrong and correct batch numbers sent to ddpm are 32 and 64. I forgot which number is correct or wrong. Do you happen to know the reason?

**Comment by Lirui-Zhao** [comment]
> Hi Lirui, I got a size miss matching issue when change GPU number from 4 to 8. The wrong and correct batch numbers sent to ddpm are 32 and 64. I forgot which number is correct or wrong. Do you happen to know the reason?

Hi @LPXTT,

Thank you for reaching out!

In [config/train.yaml](https://github.com/OpenGVLab/Diffree/blob/main/config/train.yaml), the [batch_size](https://github.com/OpenGVLab/Diffree/blob/29aee635bc566769d7a2a210fd32c93557eae2a2/config/train.yaml#L96) refers to the batch size per GPU. The total batch size is calculated as: batch_size × number of GPUs × [accumulate_grad_batches](https://github.com/OpenGVLab/Diffree/blob/29aee635bc566769d7a2a210fd32c93557eae2a2/config/train.yaml#L128).

Therefore, when changing the number of GPUs to 8, you do not need to modify any other parameters, as the total batch size will automatically scale based on the configuration.

I hope this helps clarify the issue!

Best regards,
Lirui
