### ISSUE TITLE
神作，跪求comfyui的实现...

### ISSUE THREAD

**Issue by WhiteKnight666** [OpenGVLab/Diffree#2]
如题

**Comment by Lirui-Zhao** [comment]
你好，
目前暂时还没有实现这个的计划，可能之后会去更新一下哈

**Comment by smthemex** [comment]
移植没什么难度，我做一个就是了

**Comment by Lirui-Zhao** [comment]
> 如题

你好，你现在可以通过访问@smthemex 的仓库[ComfyUI_Diffree](https://github.com/smthemex/ComfyUI_Diffree)获得comfyui的实现，感谢@smthemex 的帮助！
