### ISSUE TITLE
OABench dataset release?

### ISSUE THREAD

**Issue by apolinario** [OpenGVLab/Diffree#3]
Congratulations on the paper and the model, will you release the OABench dataset as well? Would be great to have it on https://huggingface.co/datasets

**Comment by Lirui-Zhao** [comment]
Hi,

Thank you for your interest in our work! Absolutely, we plan to release the OABench dataset and will be uploading it to Hugging Face within the next week.

Best regards,
Lirui

**Comment by George0726** [comment]
Hi Lirui,
Your data filtering workflow is amazing. Could you mind disclosing more details on edge detection, intergrity assessment, cavity inspection, etc or if we can assess your supplementary :)

Thanks,
George

**Comment by Lirui-Zhao** [comment]
Hi George,

Thank you for your kind words and interest in our work!

Our filtering process is as described in the paper. Each sub-step in the filtering involves straightforward methods. For instance, edge detection is performed by checking if the values at the edges of the mask image are all zero. We might provide more detailed information and code on the filtering process in the future, so please stay tuned.

Thank you for your patience and understanding.

Best regards,
Lirui

**Comment by shenhaibo123** [comment]
> 嗨，乔治，
> 
> 感谢您的善意以及对我们工作的关注！
> 
> 我们的过滤过程与论文中描述的一样。过滤中的每个子步骤都涉及简单的方法。例如，通过检查掩码图像边缘的值是否全为零来执行边缘检测。我们可能会在未来提供有关过滤过程的更详细信息和代码，敬请期待。
> 
> 感谢您的耐心和理解。
> 
> 谨致问候， 李瑞

您好，特别期待能够发布数据的清洗过滤过程

**Comment by Lirui-Zhao** [comment]
> Congratulations on the paper and the model, will you release the OABench dataset as well? Would be great to have it on https://huggingface.co/datasets

Hi,

We have released the dataset OABench, please check it.

Best regards,
Lirui
