### ISSUE TITLE
Release training code

### ISSUE THREAD

**Issue by AshkanTaghipour** [OpenGVLab/Diffree#4]
Hi, many thanks for releasing the inference.
Is there any plan for releasing the training code?

**Comment by Lirui-Zhao** [comment]
Hi,

We will release the training code and the OABench dataset together very soon! Thank you for your attention to our work.

Lirui

**Comment by Lirui-Zhao** [comment]
> Hi, many thanks for releasing the inference. Is there any plan for releasing the training code?

Hi,

We have released the training code, please check it.

Best regards,
Lirui
