### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [OpenGVLab/Diffree#5]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.16982.

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

## Making sure download stats work

It's great to see the model on the hub: https://huggingface.co/LiruiZhao/Diffree, however currently download stats don't work for your model, see here on how to make them work: https://huggingface.co/docs/hub/models-download-stats.

Here I would recommend leveraging the `PyTorchModelHubMixin` to push and reload the custom PyTorch model from the hub: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub. This will ensure download counts work (as a `config.json` gets pushed along with `safetensors` weights).

This way, the model would also pop up as being linked to the [Gradio Space](https://huggingface.co/spaces/LiruiZhao/Diffree).

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by Lirui-Zhao** [comment]
Hi Niels,

Thank you very much for your helpful suggestions.

I have submitted a Pull Request to enable download stats based on the instructions (https://huggingface.co/docs/hub/models-download-stats) before. However, it is still awaiting approval: https://github.com/huggingface/huggingface.js/pull/823.

I will also look into using the PyTorchModelHubMixin for push and reload the model. Thank you for pointing that out!

Best regards,
Lirui

**Comment by NielsRogge** [comment]
Hi,

Thanks for the ping, I'll ensure it gets reviewed and merged.

Would be great to try out `PyTorchModelHubMixin`!
