### ISSUE TITLE
生成进度没反应

### ISSUE THREAD

**Issue by theoldsong** [OpenGVLab/Diffree#6]
进度一直是0，GPU占用也满了，就是不生成，怎么回事？

![QQ截图20240730213858](https://github.com/user-attachments/assets/648614c7-f3c1-4b68-95a9-55321eca6082)

**Comment by Lirui-Zhao** [comment]
你好，
请问一下你这个是按照教程配环境的吗？是否有什么其他的步骤，或者是否跑的时候开代理了吗？可以提供更多的信息一下，我还没遇到过这样的情况...

**Comment by theoldsong** [comment]
> 你好， 请问一下你这个是按照教程配环境的吗？是否有什么其他的步骤，或者是否跑的时候开代理了吗？可以提供更多的信息一下，我还没遇到过这样的情况...

退出重新激活环境就可以了。感谢回复。

现在遇到了另一个问题，我自己 本地调试没问题，打包成一键包，放另一台电脑就提示报错：
No module named "k_difussion"
请问这是什么原因？

**Comment by Lirui-Zhao** [comment]
> > 你好， 请问一下你这个是按照教程配环境的吗？是否有什么其他的步骤，或者是否跑的时候开代理了吗？可以提供更多的信息一下，我还没遇到过这样的情况...
> 
> 退出重新激活环境就可以了。感谢回复。
> 
> 现在遇到了另一个问题，我自己 本地调试没问题，打包成一键包，放另一台电脑就提示报错： No module named "k_difussion" 请问这是什么原因？

感觉是环境没有完全的打包好，缺少了k-diffusion的环境，你可以通过`requirement.txt`中的`k-diffusion`那行命令手动安装，具体来说为:"pip install -e git+https://github.com/crowsonkb/k-diffusion.git@v0.0.16#egg=k-diffusion"

**Comment by theoldsong** [comment]
> > > 你好， 请问一下你这个是按照教程配环境的吗？是否有什么其他的步骤，或者是否跑的时候开代理了吗？可以提供更多的信息一下，我还没遇到过这样的情况...
> > 
> > 
> > 退出重新激活环境就可以了。感谢回复。
> > 现在遇到了另一个问题，我自己 本地调试没问题，打包成一键包，放另一台电脑就提示报错： No module named "k_difussion" 请问这是什么原因？
> 
> 感觉是环境没有完全的打包好，缺少了k-diffusion的环境，你可以通过`requirement.txt`中的`k-diffusion`那行命令手动安装，具体来说为:"pip install -e git+https://github.com/crowsonkb/k-diffusion.git@v0.0.16#egg=k-diffusion"

感谢，我试试
