### ISSUE TITLE
https://huggingface.co/spaces/LiruiZhao/Diffree   is error

### ISSUE THREAD

**Issue by jttqbc666** [OpenGVLab/Diffree#7]
![img_v3_02df_2355e536-136d-411d-845f-2a4dc48aee3g](https://github.com/user-attachments/assets/d517693e-c95e-4f3c-b3ef-fe014954a869)

https://huggingface.co/spaces/LiruiZhao/Diffree   is error

**Comment by Lirui-Zhao** [comment]
Hi,

Thank you for pointing this out! We have already fixed it. Please try again.

Best regards,
Lirui
